name: Dr Pong Web Server CI

on:
  push:
    branches:
      - /^\d+-.*$/
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set up Node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # clean install
      - name: Install dependencies
        run: npm install

      # build
      - name: Build
        run: npm run build --if-present

      # Start the database service
      # - name: Start database service
      #   run: docker-compose up -d chat-db

      # Wait for the database service to start
      # - name: Wait for database service
      #   run: |
      #     while ! PGPASSWORD=chat_db_password psql -h localhost -U chat_db_user -d chat-db -c "select 1;" > /dev/null 2>&1; do
      #       sleep 1
      #     done

      # # Run database migrations (if applicable)
      # - name: Run database migrations
      #   run: npm run db:migrate

      # Run tests
      # - name: Run tests
      #   run: npm test
